services:
  db:
    image: $DOCKER_HUB_REPO:db
    build: ./db
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  web:
    image: $DOCKER_HUB_REPO:web
    build: .
    ports:
      - $PORT:$PORT
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGHOST=db
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
      - PGPORT=$PGPORT
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - TABLE=$TABLE
      - LOG_LEVEL=$LOG_LEVEL
    volumes:
      - $CERT_PATH:$CERT_PATH
      - $KEY_PATH:$KEY_PATH
