name: Build/Deploy to Docker Hub
on:
  push:
    branches:
      - "main"

jobs:
  checkout:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
  build:
    needs: checkout
    runs-on: [self-hosted, macOS, X64]
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Deploy
      run: docker compose build --push
      env:
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
        PGPORT: ${{ secrets.PGPORT }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TABLE: ${{ secrets.TABLE }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        PORT: ${{ secrets.PORT }}
        ENV: prod
        DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}
        KEY_PATH: ${{ secrets.KEY_PATH }}
        CERT_PATH: ${{ secrets.CERT_PATH }}



