name: Build/Deploy to Docker Hub
on:
  push:
    branches:
      - "main"

jobs:
  checkout:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
  build:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Build and Deploy
        run: docker compose build --push

